data:
  sampling_rate: 44100
  block_size: 512
  encoder: "hubert"
  encoder_sample_rate: 16000
  encoder_hop_size: 320
  encoder_out_channels: 256

model:
  hidden_size: 512
  n_layers: 6
  n_heads: 8
  window_size: 16
  conv_channels: [512, 512, 512]
  dropout: 0.1

training:
  batch_size: 16
  learning_rate: 0.0001
  warmup_steps: 1000
  max_steps: 100000