hubert:
  model_type: "hubert_soft"
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072

rmvpe:
  hop_length: 512
  f0_min: 50
  f0_max: 1100
  model_sampling_rate: 16000

enhancer:
  type: "nsf_hifigan"
  resblock_kernel_sizes: [3, 7, 11]
  upsample_rates: [8, 8, 2, 2]
  upsample_kernel_sizes: [16, 16, 4, 4]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]