server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 600
  ssl_enabled: false

cors:
  allow_origins: ["*"]
  allow_methods: ["*"]
  allow_headers: ["*"]

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/server.log"

security:
  token_expire_minutes: 60
  secret_key: "your-secret-key-here"